version: 0.0
os: linux
files:
  - source: /
    destination: /apps/rails
permissions:
  - object: /apps/rails/bin
    pattern: "**"
    owner: app
    mode: 755
    type:
      - file
  - object: /apps/rails/ops
    pattern: "**"
    owner: app
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: ops/install_deps.sh
      timeout: 600
    - location: ops/install_app.sh
      timeout: 300
      runas: app
  ApplicationStart:
    - location: ops/start_app.sh
      timeout: 180
      runas: app
  ValidateService:
    - location: ops/verify_app.sh
